# Generated by Django 6.0.3 on 2026-04-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='cap_id_curso',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
