# Generated by Django 6.0.3 on 2026-04-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_cap_id_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='cap_nombre',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='pob_tipo',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
