# Generated by Django 6.0.3 on 2026-04-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ampliar_campos_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='diag_generacion_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='diag_instrumento_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='diag_matriz_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='diag_problemas_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='diag_resultados_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='gr_cronograma_campos_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='mi_competencias_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='mi_desempenos_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='mi_formula_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='mi_malla_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='pt_productos_indicadores_json',
            field=models.TextField(blank=True, default=''),
        ),
    ]
