# Generated by Django 6.0.3 on 2026-04-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_agregar_priorizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='pt_convocatoria_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='pt_convocatoria_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='pt_implementacion_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='pt_implementacion_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='cap_estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('En proceso', 'En Proceso'), ('Por finalizar', 'Por Finalizar'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Borrador', max_length=30),
        ),
    ]
