# Generated by Django 6.0.3 on 2026-04-17 17:00

from django.db import migrations, models
from django.db.models import Q


def normalizar_estados_existentes(apps, schema_editor):
    Capacitacion = apps.get_model('core', 'Capacitacion')

    # Renombra el estado inicial antiguo para mostrarlo como Formulada.
    Capacitacion.objects.filter(cap_estado='Borrador').update(cap_estado='Formulada')

    # Corrige casos 2026 que estaban marcados como cierre sin haber completado el flujo.
    Capacitacion.objects.exclude(cap_estado='Cancelada').filter(
        cap_anio__gte=2026,
        paso_actual__lt=7,
        cap_estado__in=['Finalizada', 'Por finalizar'],
    ).update(cap_estado='En proceso')

    # Si no hay código ni ID de curso, debe permanecer en estado inicial.
    Capacitacion.objects.exclude(cap_estado='Cancelada').filter(
        Q(cap_codigo__isnull=True) | Q(cap_codigo=''),
        Q(cap_id_curso__isnull=True) | Q(cap_id_curso=''),
    ).update(cap_estado='Formulada')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_capacitacion_pt_convocatoria_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='cap_estado',
            field=models.CharField(choices=[('Formulada', 'Formulada'), ('Borrador', 'Borrador'), ('En proceso', 'En Proceso'), ('Por finalizar', 'Por Finalizar'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Formulada', max_length=30),
        ),
        migrations.RunPython(normalizar_estados_existentes, migrations.RunPython.noop),
    ]
