# Generated by Django 6.0.3 on 2026-04-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_capacitacion_pt_convocatoria_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='cap_estado',
            field=models.CharField(choices=[('Formulada', 'Formulada'), ('Borrador', 'Borrador'), ('En proceso', 'En Proceso'), ('Por finalizar', 'Por Finalizar'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Formulada', max_length=30),
        ),
    ]
