# Generated by Django 6.0.3 on 2026-04-17 17:31

import django.db.models.deletion
from django.db import migrations, models


def recalcular_estados_2026(apps, schema_editor):
    Capacitacion = apps.get_model('core', 'Capacitacion')
    conn = schema_editor.connection

    for cap in Capacitacion.objects.exclude(cap_estado='Cancelada').filter(cap_anio__gte=2026):
        tiene_codigo = bool(str(cap.cap_codigo or '').strip())
        tiene_id = bool(str(cap.cap_id_curso or '').strip())

        if not tiene_codigo and not tiene_id:
            nuevo = 'Formulada'
        else:
            codigo_completo = str(cap.cap_codigo or '').strip()
            if cap.cap_id_curso:
                codigo_completo = f"{codigo_completo}-{str(cap.cap_id_curso).strip()}"

            pasos_completos = int(cap.paso_actual or 0) >= 7
            tiene_certificados = False
            if codigo_completo:
                try:
                    with conn.cursor() as cursor:
                        cursor.execute(
                            "SELECT 1 FROM bbdd_difoca WHERE codigo = %s AND aprobados_certificados = 1 LIMIT 1",
                            [codigo_completo],
                        )
                        tiene_certificados = bool(cursor.fetchone())
                except Exception:
                    tiene_certificados = False

            if pasos_completos and tiene_certificados:
                nuevo = 'Finalizada'
            elif pasos_completos or tiene_certificados:
                nuevo = 'Por finalizar'
            else:
                nuevo = 'En proceso'

        if str(cap.cap_estado or '') != nuevo:
            cap.cap_estado = nuevo
            cap.save(update_fields=['cap_estado'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_normalizar_estados_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapSincronicaProcesamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=120)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('output_file', models.CharField(blank=True, default='', max_length=255)),
                ('output_blob', models.BinaryField(blank=True, null=True)),
                ('stats_json', models.TextField(blank=True, default='{}')),
                ('procesado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('capacitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procesamientos_sincronicos', to='core.capacitacion')),
            ],
            options={
                'db_table': 'cap_sincronica_procesamiento',
                'ordering': ['-procesado_en'],
                'constraints': [models.UniqueConstraint(fields=('codigo', 'input_hash'), name='uniq_sync_codigo_hash')],
            },
        ),
        migrations.RunPython(recalcular_estados_2026, migrations.RunPython.noop),
    ]
