# Generated by Django 6.0.3 on 2026-06-24 14:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_unique_cap_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacitacion',
            name='cap_nombre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='capacitacion',
            name='pt_horas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='capmallacurricular',
            name='horas',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='capsincronicaprocesamiento',
            name='capacitacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procesamientos_sincronicos', to='core.capacitacion'),
        ),
        migrations.AlterField(
            model_name='dniexcluido',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='capcompetencia',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_competencias_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capcronogramacampo',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_cronograma_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capdesempenio',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_desempenios_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capdimension',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_dimensiones_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capformulaevaluacion',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_formula_eval_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capgeneracionoperativa',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_generacion_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capindicador',
            index=models.Index(fields=['subdimension', 'orden'], name='idx_indicadores_sub_ord'),
        ),
        migrations.AddIndex(
            model_name='capinstrumentoitem',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_instrumento_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capmallacurricular',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_malla_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capmatrizindicador',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_matriz_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capproblema',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_problemas_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capproductoindicador',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_productos_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capresultadoesperado',
            index=models.Index(fields=['capacitacion', 'orden'], name='idx_resultados_cap_ord'),
        ),
        migrations.AddIndex(
            model_name='capsubdimension',
            index=models.Index(fields=['dimension', 'orden'], name='idx_subdimensiones_dim_ord'),
        ),
    ]
