# Generated by Django 6.0.3 on 2026-07-30 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_fix_cap_nombre_maxlen_sync_fk_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(db_index=True, max_length=150)),
                ('otorgado_por', models.CharField(max_length=150)),
                ('otorgado_nombre', models.CharField(blank=True, default='', max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_reporte', to='core.capacitacion')),
            ],
            options={
                'verbose_name': 'Acceso a reporte',
                'verbose_name_plural': 'Accesos a reportes',
                'db_table': 'cap_acceso_reporte',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['email', 'activo'], name='idx_acceso_email_activo')],
                'constraints': [models.UniqueConstraint(fields=('capacitacion', 'email'), name='uniq_acceso_reporte_cap_email')],
            },
        ),
    ]
