# Generated by Django 6.0.3 on 2026-07-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_accesoreporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='especialista_usuario',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
    ]
