# Generated by Django 5.2.17 on 2026-08-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_poblar_especialista_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigJson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clave", models.CharField(max_length=100, unique=True)),
                ("valor", models.TextField(default="{}")),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuración JSON",
                "verbose_name_plural": "Configuraciones JSON",
                "db_table": "cap_config_json",
            },
        ),
        migrations.CreateModel(
            name="ArchivoGenerado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(db_index=True, max_length=120)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("main", "Plantilla generada"),
                            ("nominal", "Reporte nominal"),
                            ("iged", "Cumplimiento por IGED"),
                            ("cumplimiento", "Reporte de cumplimiento (visores)"),
                            ("postulantes", "Excel de postulantes"),
                        ],
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("contenido", models.BinaryField()),
                ("size_bytes", models.PositiveIntegerField(default=0)),
                ("anio", models.IntegerField(blank=True, null=True)),
                ("generado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Archivo generado",
                "verbose_name_plural": "Archivos generados",
                "db_table": "cap_archivos_generados",
                "ordering": ["codigo", "kind"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("codigo", "kind"), name="uniq_archivo_generado_cod_kind"
                    )
                ],
            },
        ),
    ]
