# Generated by Django 6.0.3 on 2026-08-12 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_poblar_especialista_usuario"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccionPlataforma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, unique=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "creado_por",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Acción de plataforma",
                "verbose_name_plural": "Acciones de plataforma",
                "db_table": "cap_casuistica_accion",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Casuistica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_visor", models.CharField(db_index=True, max_length=150)),
                (
                    "nombre_visor",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("dni_participante", models.CharField(db_index=True, max_length=15)),
                (
                    "nombre_participante",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("asunto", models.CharField(max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierto", "Abierto"),
                            ("en_plataforma", "En plataforma"),
                            ("cerrado", "Cerrado"),
                        ],
                        db_index=True,
                        default="abierto",
                        max_length=20,
                    ),
                ),
                (
                    "turno",
                    models.CharField(
                        blank=True,
                        choices=[("visor", "Visor"), ("admin", "Administrador")],
                        default="admin",
                        max_length=10,
                    ),
                ),
                ("accion_definida_en", models.DateTimeField(blank=True, null=True)),
                (
                    "accion_definida_por",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                ("cerrado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "cerrado_por",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("veces_reabierto", models.PositiveIntegerField(default=0)),
                ("exportado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "exportado_por",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "accion_a_realizar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casuisticas",
                        to="core.accionplataforma",
                    ),
                ),
                (
                    "capacitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="casuisticas",
                        to="core.capacitacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Casuística",
                "verbose_name_plural": "Casuísticas",
                "db_table": "cap_casuistica",
                "ordering": ["-actualizado_en"],
            },
        ),
        migrations.CreateModel(
            name="CasuisticaMensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("mensaje", "Mensaje"),
                            ("cambio_estado", "Cambio de estado"),
                            ("reapertura", "Reapertura"),
                        ],
                        default="mensaje",
                        max_length=20,
                    ),
                ),
                (
                    "autor_tipo",
                    models.CharField(
                        choices=[
                            ("visor", "Visor"),
                            ("admin", "Administrador"),
                            ("sistema", "Sistema"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "autor_nombre",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "autor_email",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("texto", models.TextField(blank=True, default="")),
                ("creado_en", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "casuistica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensajes",
                        to="core.casuistica",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensaje de casuística",
                "verbose_name_plural": "Mensajes de casuística",
                "db_table": "cap_casuistica_mensaje",
                "ordering": ["creado_en"],
            },
        ),
        migrations.CreateModel(
            name="CasuisticaEvidencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=100)),
                (
                    "nombre_original",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("mime_type", models.CharField(blank=True, default="", max_length=100)),
                ("tamano_bytes", models.PositiveIntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("purgada_en", models.DateTimeField(blank=True, null=True)),
                (
                    "mensaje",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidencias",
                        to="core.casuisticamensaje",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidencia de casuística",
                "verbose_name_plural": "Evidencias de casuística",
                "db_table": "cap_casuistica_evidencia",
                "ordering": ["creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="casuistica",
            index=models.Index(
                fields=["capacitacion", "estado"], name="idx_casuistica_cap_estado"
            ),
        ),
        migrations.AddIndex(
            model_name="casuistica",
            index=models.Index(
                fields=["email_visor", "estado"], name="idx_casuistica_visor_estado"
            ),
        ),
    ]
