# Generated by Django 6.0.3 on 2026-08-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_casuisticas"),
    ]

    operations = [
        migrations.AddField(
            model_name="casuistica",
            name="accion_detalle",
            field=models.TextField(blank=True, default=""),
        ),
    ]
