# Generated by Django 6.0.3 on 2026-08-14 20:52

from django.db import migrations, models

# Lista provista por el usuario (14-ago-2026). codigo_iged_texto conserva los
# ceros a la izquierda tal como se recibieron; codigo_iged es la version
# entera usada para el join contra bbdd_difoca.codigo_iged (columna double).
# Un mismo codigo puede repetirse en varios ambitos (ej. 160003 esta en ACF,
# FRONTERA y PETROLERO simultaneamente) - eso es intencional, no un duplicado.
AMBITOS_ESPECIALES_SEED = {
    "ACF": [
        "160003", "250001", "010010", "010011", "160001", "250004",
        "160008", "160005", "160006", "060009", "210012", "230001",
    ],
    "FRONTERA": [
        "170000", "200000", "210000", "230000", "240000", "160003",
        "200005", "010002", "210005", "250001", "210004", "200006",
        "210006", "010009", "010010", "010011", "160004", "160001",
        "210008", "210001", "250004", "160008", "160005", "160006",
        "210007", "060009", "210012", "200010", "230001", "170003",
        "200002", "170001", "230003", "240001", "210013", "240003",
    ],
    "PETROLERO": [
        "160000", "160002", "160003", "160004", "160001", "160006",
    ],
    "VRAEM": [
        "030002", "030006", "090005", "120003", "030008", "120001",
        "050004", "080009", "050005", "120010", "080014", "120014",
        "120012", "120007", "090009", "090007",
    ],
}


def seed_ambitos_especiales(apps, schema_editor):
    IgedAmbitoEspecial = apps.get_model("core", "IgedAmbitoEspecial")
    filas = [
        IgedAmbitoEspecial(
            codigo_iged=int(codigo_texto),
            codigo_iged_texto=codigo_texto,
            ambito=ambito,
        )
        for ambito, codigos in AMBITOS_ESPECIALES_SEED.items()
        for codigo_texto in codigos
    ]
    IgedAmbitoEspecial.objects.bulk_create(filas, ignore_conflicts=True)


def eliminar_seed_ambitos_especiales(apps, schema_editor):
    IgedAmbitoEspecial = apps.get_model("core", "IgedAmbitoEspecial")
    IgedAmbitoEspecial.objects.filter(ambito__in=AMBITOS_ESPECIALES_SEED.keys()).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_casuistica_accion_detalle"),
    ]

    operations = [
        migrations.CreateModel(
            name="IgedAmbitoEspecial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_iged", models.IntegerField(db_index=True)),
                (
                    "codigo_iged_texto",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("ambito", models.CharField(db_index=True, max_length=50)),
                (
                    "nombre_iged",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "IGED en ámbito especial",
                "verbose_name_plural": "IGEDs en ámbitos especiales",
                "db_table": "cap_iged_ambitos_especiales",
                "ordering": ["ambito", "codigo_iged"],
                "unique_together": {("codigo_iged", "ambito")},
            },
        ),
        migrations.RunPython(seed_ambitos_especiales, eliminar_seed_ambitos_especiales),
    ]
