# Generated by Django 6.0.3 on 2026-08-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_iged_ambitos_especiales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casuistica",
            name="estado",
            field=models.CharField(
                choices=[
                    ("abierto", "Abierto"),
                    ("en_plataforma", "En plataforma"),
                    ("cerrado", "Cerrado"),
                    ("anulado", "Anulado"),
                ],
                db_index=True,
                default="abierto",
                max_length=20,
            ),
        ),
    ]
